### ISSUE TITLE
При использовании testit.addAttachments - ERROR Upload attachment <path> status: name 'is_temp' is not defined

### ISSUE THREAD

**Issue by Sirinox** [testit-tms/adapters-python#120]
### Проблема:
при использовании testit.addAttachments возникает ошибка в логах

```
2023-12-21 15:12:08 ERROR Upload attachment "C:\Users\User\project\test_ui\test_unauthorized\scr\test_ui_reg_animation_scr_1.png" status: name 'is_temp' is not defined
2023-12-21 15:12:08 ERROR Upload attachment "C:\Users\User\project\test_ui\test_unauthorized\scr\test_ui_reg_animation_scr_1.png" status: name 'is_temp' is not defined
```

В результате скриншоты в tms не приходят.
![image](https://github.com/testit-tms/adapters-python/assets/102709819/4627efda-c5ad-4fb9-aa1f-eee67a4dd09f)

### Ожидаемый результат:
![image](https://github.com/testit-tms/adapters-python/assets/102709819/99572b61-52ba-46d0-a917-3ef8a1870798)

### Версии:
testit-adapter-pytest==2.5.2
testit-api-client==3.4.1
testit-python-commons==2.5.2

### Комментарий:
В testit_api_client\model\attachment_model.py
есть функция 
`def _from_openapi_data(cls, file_id, type, size, created_date, created_by_id, name, is_temp, id, *args, **kwargs)`
где как раз расположен параметр is_temp, на который ругаются логи, потому что он обязательный.
Если убрать этот параметр из функции и добавить его в код как
is_temp = False
то будет работать - таким образом я и получил скрин ожидаемого результата.

**Comment by OddanN** [comment]
А какой функцией отправляете скриншоты?

**Comment by Sirinox** [comment]
> А какой функцией отправляете скриншоты? 

В коде теста:
![image](https://github.com/testit-tms/adapters-python/assets/102709819/9247fda0-6381-4d2f-980b-f7dffd33f27a)

код функции "attach_screenshot"
![image](https://github.com/testit-tms/adapters-python/assets/102709819/dcbe21f7-7eb8-4bd2-8268-634526efeb97)


> И какая версия TestIT?

Продукт: | Test IT Enterprise
-- | --
Версия: | 4.4.0
Сборка: | 4.4.0
Базовый образ: | debian
Дата: | 11.09.23 17:55:21

**Comment by OddanN** [comment]
https://github.com/testit-tms/adapters-python/tree/main#compatibility
![image](https://github.com/testit-tms/adapters-python/assets/24387880/8139dade-2b63-4f29-b060-d6ae54622e71)

Обновите ТестИТ или сделайте даунгрейд адаптера

**Comment by Sirinox** [comment]
> Обновите ТестИТ или сделайте даунгрейд адаптера

Обновление до 4.5 решило проблему. Спасибо!
