### ISSUE TITLE
Не запускаются тесты с флагом --testit после обновления testit_adapter_pytest

### ISSUE THREAD

**Issue by DKorolev94** [testit-tms/adapters-python#137]
Я обращаюсь с проблемой, связанной с использованием testit_adapter_pytest версии 2.8.0 - 2.8.3. После обновления до этих версий, мои тесты перестали запускаться при использовании команды в терминале:

pytest -v tests/consumer/test_main_page.py::TestMainPage::test_pagination_on_scroll_main --testit

Без флага --testit тесты работают нормально, однако при его указании возникает следующая ошибка.

Проблема не возникает при использовании старой версии testit_adapter_pytest (2.5.2) в старом виртуальном окружении venv.

Ниже привожу пример ошибки:

![image](https://github.com/testit-tms/adapters-python/assets/128136032/36c20113-8830-4ae2-898d-d347d7ed50ed)

![image](https://github.com/testit-tms/adapters-python/assets/128136032/23225685-2f69-488a-b013-2b54bb1a83e6)

**Comment by dmitriy-belkin** [comment]
Когда testit пофиксят эту проблему?) Люди уже давно столкнулись с трудностями. Мне изменения из обсуждений и понижение версий не помогают((

**Comment by komissarov-petr** [comment]
> Когда testit пофиксят эту проблему?) Люди уже давно столкнулись с трудностями. Мне изменения из обсуждений и понижение версий не помогают((

Добрый день, в версии [3.1.0](https://github.com/testit-tms/adapters-python/releases) добавили поддержку pytest 8.1.0
