### ISSUE TITLE
Декоратор `@testit.workItemIds` не поддерживает несколько `workitemids`

### ISSUE THREAD

**Issue by demugen** [testit-tms/adapters-python#153]
**Описание:**

В настоящее время декоратор `@testit.workItemIds()` не поддерживает передачу нескольких идентификаторов `workitemids`. Это ограничение вызывает проблемы, когда необходимо указать несколько идентификаторов ТК для одной и той же функции тестирования. Фактически обрабатывается и привязывается только первый идентификатор.

**Примеры:**

#### Ожидаемое поведение:
```python
@testit.workItemIds(627, 628, 629)
def test_function():
    # Функция теста
    pass

# Ожидается, что test_function будет иметь атрибут test_workitems_id с значениями ['627', '628', '629']. В TestIT будут выгружены связи для трех ТК : '627', '628', '629'. Но в TestIT отобразится привязка только к первому ID.

```

**Шаги для воспроизведения:**

1. Создать функцию с декоратором `@testit.workItemIds(627, 628, 629)`.
2. Запустить тест.

**Ожидаемый результат:**

Функция теста должна поддерживать несколько `workitemids`, переданных в декоратор. Тесты будут иметь привязку к трем ТК.

**Фактический результат:**

Функция теста поддерживает только первый `workitemid`.

----
testit-adapter-pytest==3.2.2
testit-api-client==4.0.0
testit-python-commons==3.2.2

**Comment by demugen** [comment]
Вероятно проблема в функции "__get_work_item_ids_from", по идее вот исправленный вариант.

```python
def __get_work_item_ids_from(item):
    test_workitems_id = __search_attribute(item, 'test_workitems_id')

    if not test_workitems_id:
        return []

    all_parameters = get_all_parameters(item)

    if not all_parameters:
        return test_workitems_id

    result = []
    for workitem_id in test_workitems_id:
        processed_id = collect_parameters_in_mass_attribute(workitem_id, all_parameters)
        if isinstance(processed_id, __ARRAY_TYPES):
            result.extend(map(str, processed_id))
        else:
            result.append(str(processed_id))
    return result

```

**Comment by tashlykovamur1** [comment]
Почините пожалуйста баг! 
Сейчас невозможно связывать несколько ручных тестов. Обходной костыль тоже не получилось сделать

**Comment by iromanchenko-cyrm** [comment]
Так же самая проблема. Почините, пожалуйста!

**Comment by grybakov** [comment]
Тоже стреляет в ногу(. В саппорт никто не писал?

**Comment by tashlykovamur1** [comment]
В саппорте ответили вот так. Видимо остается только ждать:

> сть задача у наших разработчиков на доработку поведения
Номер TMS-26720
Говорят, что возьмут в ближайших спринтах

**Comment by tashlykovamur1** [comment]
@demugen может просто форкнуть твой кусок исправленный в репозиторий? Всем бы людям тут помог

**Comment by taipoxinous** [comment]
@demugen @tashlykovamur1 @iromanchenko-cyrm @grybakov исправлено в 3.2.6.
