### ISSUE TITLE
Поддержать pytest-check 1.1.3

### ISSUE THREAD

**Issue by OddanN** [testit-tms/adapters-python#37]
В pytest-check 1.1.3 поменялась структура, из-за этого testit_adapter_pytest падает.
self = <testit_adapter_pytest.listener.TmsListener object at 0x00000231AF54AAC0>

    @adapter.hookimpl
    def get_pytest_check_outcome(self):
        if self.__pytest_check_get_failures:
           from pytest_check import check_methods

E           ImportError: cannot import name 'check_methods' from 'pytest_check' (\venv\lib\site-packages\pytest_check\__init__.py)

venv\lib\site-packages\testit_adapter_pytest\listener.py:42: ImportError

https://github.com/okken/pytest-check/blob/main/src/pytest_check/__init__.py

**Comment by testit-owner** [comment]
Добрый день!
Работа с пакетом pytest-check 1.1.3 поддержана в версии адаптера 2.0.8.
Благодарим за обращение!
