### ISSUE TITLE
Игнорирование параметра indirect для параметризованных тестов

### ISSUE THREAD

**Issue by lozzzt** [testit-tms/adapters-python#39]
Игнорируется параметр indirect для pytest.mark.parametrize
и testit вместо результата выполнения фикстуры get_all_params (из нижеприведенного примера) считает get_all_params именем параметра, 
соответственно get_all_params[1] будет расцениваться в коде метода, как NAME, 
а в декораторах @testit как EXT_ID

```
    @pytest.fixture()
    def get_all_params(request, get_id_by_name):
        return get_id_by_name(request.param[0]), *request.param

    P = [
        ["NAME1", "EXT_ID1", "WORK_ID1"],
        ["NAME2", "EXT_ID2", "WORK_ID2"],
    ]

    @testit.displayName("NAME: {get_all_params[1]}")
    @testit.description("DESCRIPTION: {get_all_params[1]}")
    @testit.externalId("{get_all_params[2]}")
    @testit.workItemIds("{get_all_params[3]}")
    @pytest.mark.parametrize("get_all_params", P, ids=lambda p: p[0], indirect=True)
    def test_method(get_all_params):
        print(get_all_params[0])  # id
        print(get_all_params[1])  # name
        print(get_all_params[2])  # ext_id
        print(get_all_params[3])  # work_id
```

**Comment by lozzzt** [comment]
Неактуально

**Comment by OddanN** [comment]
@lozzzt а как решили проблему?

**Comment by lozzzt** [comment]
> @lozzzt а как решили проблему?

1. Параметры тестов, такие, как имя, externalId, workID не требуется вычислять - я их знаю заранее, поэтому просто в моём примере в декораторах индекс на 1 меньше ставлю.
2. Думаю технически почти невозможно результат indirect-фикстуры в декораторы передавать, поэтому просто смирился с особенностью :)
