### ISSUE TITLE
Отбор тестов при запуске с параметром -m

### ISSUE THREAD

**Issue by dmtrbrlkv** [testit-tms/adapters-python#5]
В данный момент после обработки коллекции тестов в хуке pytest_collection_modifyitems перестает учитываться параметр pytest для отбора тестов по маркам -m

**Comment by testit-tms** [comment]
Приносим извинения за долгое ожидание.
Фикс https://github.com/testit-tms/adapters-python/pull/6, сделанный Вами, был добавлен в основную ветку. Большое спасибо за помощь в улучшении функционала!
