### ISSUE TITLE
Добавление шагов из классовых фикстур

### ISSUE THREAD

**Issue by ematrosova** [testit-tms/adapters-python#7]
Сейчас стоит запрет на добавление шагов (testit.step) из классовых фикстур (scope="class").
Хотелось бы, чтобы в автотесте можно было видеть шаги и время их выполнения из всех фикстур.

**Comment by Eldackar** [comment]
Интересно, меня то же самое интересовало

**Comment by PavelButuzov** [comment]
Добрый день!
Добавление шагов из фикстур Pytest реализовано в версии адаптера 2.4.0.
Благодарим за обращение!
